
create table fruit_with_identity_seed (
	fruit_id int generated always as identity (start with 10 increment by 10),
	fruit_name varchar(100) not null
);

insert into fruit_with_identity_seed (fruit_name)
values ('pomelo'),('orangu'),('bambinito');


select * from fruit_with_identity_seed; 

CREATE TABLE fruit_identity_defaulted ( 
	fruit_id INT GENERATED By Default AS IDENTITY, 
	fruit_name VARCHAR NOT NULL 
);

insert into fruit_identity_defaulted (fruit_name)
values ('pomelo'),('orangu'),('bambinito');


select * from fruit_identity_defaulted; 