CREATE ROLE event_db_user WITH
	LOGIN
	NOSUPERUSER
	CREATEDB
	CREATEROLE
	INHERIT
	NOREPLICATION
	NOBYPASSRLS
	CONNECTION LIMIT -1
	PASSWORD 'xxxxxx';

GRANT event_db_user TO pg_database_owner WITH ADMIN OPTION;

