/*
Table 3-4. SQL Server Isolation Levels
---------------------------------------------------------------------------------------------------
Isolation Level						Description
---------------------------------------------------------------------------------------------------
READ COMMITTED (this is the default While READ COMMITTED is used, uncommitted data
behavior of SQL Server)				modifications can’t be read. Shared locks are used during a
									query, and data cannot bemodified by other processes
									while the query is retrieving the data. Data inserts and
									modifications to the same table are allowed by other
									transactions, so long as the rows involved are not locked
									by the first transaction.
READ UNCOMMITTED	This is the least restrictive isolation level, issuing no locks
					on the data selected by the transaction. This provides the
					highest concurrency but the lowest amount of data integrity,
					as the data that you read can be changed while you read it
					(asmentioned previously, these reads are known as dirty
					reads), or new data can be added or removed that would
					change your original query results. This option allows you to
					read data without blocking others but with the danger of
					reading data “in flux” that could bemodified during the read
					itself (including reading data changes froma transaction
					that ends up getting rolled back). For relatively static and
					unchanging data, this isolation level can potentially improve
					performance by instructing SQL Server not to issue
					unnecessary locking on the accessed resources.
REPEATABLE READ		When enabled, dirty and non-repeatable reads are not
					allowed. This is achieved by placing shared locks on all read
					resources. New rows thatmay fall into the range of data
					returned by your query can, however, still be inserted by
					other transactions.
SERIALIZABLE		When enabled, this is themost restrictive setting. Range
					locks are placed on the data based on the search criteria
					used to produce the result set. This ensures that actions such
					as insertion of new rows,modification of values, or deletion
					of existing rows that would have been returned within the
					original query and search criteria are not allowed.
SNAPSHOT			This isolation level allows you to read a transactionally
					consistent version of the data as it existed at the beginning of
					a transaction. Data reads do not block datamodifications—
					however, the SNAPSHOT session will not detect changes being
					made.
---------------------------------------------------------------------------------------------------

This recipe demonstrates how to use the SET TRANSACTION ISOLATION LEVEL command to set the
default transaction locking behavior for Transact-SQL statements used in a connection. You can
have only one isolation level set at a time, and the isolation level does not change unless explicitly
set. SET TRANSACTION ISOLATION LEVEL allows you to change the locking behavior for a specific
database connection. The syntax for this command is as follows:

SET TRANSACTION ISOLATION LEVEL
{ READ UNCOMMITTED
| READ COMMITTED
| REPEATABLE READ
| SNAPSHOT
| SERIALIZABLE
}

In this first example, SERIALIZABLE isolation is used to query the contents of a table. In the first
query editor window, the following code is executed:
*/

USE AdventureWorks
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE 
GO

BEGIN TRAN

SELECT AddressTypeID, Name
FROM Person.AddressType
WHERE AddressTypeID BETWEEN 1 AND 6

-- In a second query editor, the following query is executed to view the kinds of locks generated by
-- the SERIALIZABLE isolation level:

SELECT resource_associated_entity_id, resource_type,
request_mode, request_session_id
FROM sys.dm_tran_locks

--Back in the first query editor window, execute the following code to end the transaction and
--remove the locks:

COMMIT TRAN

--In contrast, the same query is executed again in the first query editor window, this time using
--the READ UNCOMMITTED isolation level to read the range of rows:

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
GO

BEGIN TRAN
SELECT AddressTypeID, Name
FROM Person.AddressType
WHERE AddressTypeID BETWEEN 1 AND 6

-- In a second query editor, the following query is executed to view the kinds of locks generated
-- by the READ UNCOMMITTED isolation level:

SELECT resource_associated_entity_id, resource_type,
request_mode, request_session_id
FROM sys.dm_tran_locks


--Unlike SERIALIZABLE, the READ UNCOMMITTED isolation level creates no additional locks on the
--keys of the Person.AddressType table.
--Returning back to the first query editor with the READ UNCOMMITTED query, the transaction is
--ended for cleanup purposes:

COMMIT TRAN

-- I’ll demonstrate the SNAPSHOT isolation level next. In the first query editor window, the following
-- code is executed:

ALTER DATABASE AdventureWorks2008
SET ALLOW_SNAPSHOT_ISOLATION ON 
GO

USE AdventureWorks2008
GO
SET TRANSACTION ISOLATION LEVEL SNAPSHOT
GO

BEGIN TRAN
SELECT CurrencyRateID,
EndOfDayRate
FROM Sales.CurrencyRate
WHERE CurrencyRateID = 8317

-- In a second query editor window, the following query is executed:
USE AdventureWorks
GO

UPDATE Sales.CurrencyRate
SET EndOfDayRate = 1.00
WHERE CurrencyRateID = 8317

-- Now back to the first query editor, the following query is reexecuted:

SELECT CurrencyRateID,
EndOfDayRate
FROM Sales.CurrencyRate
WHERE CurrencyRateID = 8317

-- The same results are returned as before, even though the row was updated by the second query
-- editor query. The SELECT was not blocked fromreading the row, nor was the UPDATE blocked from
-- making themodification.
-- Now I amgoing to commit the transaction and reissue the query:

COMMIT TRAN

SELECT CurrencyRateID,
EndOfDayRate
FROM Sales.CurrencyRate
WHERE CurrencyRateID = 8317

--+This returns the updated value:

