/*
Revealing Rows Generated by GROUPING

You may have noticed that those rows that were grouped in the previous recipes had NULL values in
the columns that weren’t participating in the aggregate totals. For example, when shelf C was totaled
up, the location and product name columns were NULL:

------------------------------
C NULL NULL 236
------------------------------

The NULL values are acceptable if your data doesn’t explicitly contain NULLs—however, what if it
does? How can you differentiate “stored” NULLs from those generated in the rollups, cubes, and
grouping sets?

In order to address this issue, you can use the GROUPING and GROUPING_ID functions.

*/

SELECT	i.Shelf,
		i.LocationID,
		CASE WHEN GROUPING(i.Shelf) = 0 AND	GROUPING(i.LocationID) = 1 THEN 'Shelf Total'
			 WHEN GROUPING(i.Shelf) = 1 AND GROUPING(i.LocationID) = 0 THEN 'Location Total'
			 WHEN GROUPING(i.Shelf) = 1 AND GROUPING(i.LocationID) = 1 THEN 'Grand Total'
		ELSE 'Regular Row' END RowType,
		SUM(i.Quantity) Total
FROM Production.ProductInventory i
WHERE LocationID = 2
GROUP BY CUBE (i.Shelf,i.LocationID)

/*
The GROUPING function allows you to differentiate and act upon those rows that are generated automatically
for aggregates using CUBE, ROLLUP, and GROUPING SETS. In this example, I started off the SELECT statement 
as normal, with the Shelf and Location columns:

	SELECT
	i.Shelf,
	i.LocationID,

Following this, I then began a CASE statement that would evaluate the combinations of return
values for the GROUPING statement. 

When GROUPING returns a 1 value (true), it means the column NULL is not an actual data value,
but is a result of the aggregate operation, standing in for the value “all”. So for example, if the shelf
value is not NULL and the location ID is null due to the CUBE aggregation process and not the data
itself, the string Shelf Total is returned:

	CASE
	WHEN GROUPING(i.Shelf) = 0 AND
	GROUPING(i.LocationID) = 1 THEN 'Shelf Total'

This continues with similar logic, only this time if the shelf value is NULL due to the CUBE aggregation
process, but the location is not null, a location total is provided:

	WHEN GROUPING(i.Shelf) = 1 AND
	GROUPING(i.LocationID) = 0 THEN 'Location Total'

The last WHEN defines when both shelf and location are NULL due to the CUBE aggregation
process, which means the row contains the grand total for the result set:

	WHEN GROUPING(i.Shelf) = 1 AND
	GROUPING(i.LocationID) = 1 THEN 'Grand Total'

GROUPING only returns a 1 or a 0; however, in SQL Server 2008, you also have the option of using
GROUPING_ID to compute grouping at a finer grain, as I’ll demonstrate in the next recipe.

*/



